### ISSUE TITLE
NPCs appearing, but interaction cylinders not

### ISSUE THREAD

**Issue by Hydraxonn** [justalemon/FoodShops#11]
Pretty much as the title says. Interaction cylinders appear in the original map, but not in mod maps like Liberty City or Vice City. The blips appear no problem, the NPC behind the counter appears no problem, but the interaction cylinder is nowhere to be found. I wish I could give more info, but that's all I've got for now. If you need further info or testing please let me know!

**Comment by justalemon** [comment]
This was a problem with the interior check. It was fixed on 05b56980de66066bcf10015e881d0e5707266ab2.
