### ISSUE TITLE
Setting interior to null in location JSONs does not work

### ISSUE THREAD

**Issue by Hydraxonn** [justalemon/FoodShops#7]
When attempting to create food shops for Liberty City and Vice City, there are many areas that don't use the traditional interior system. When attempting to set the interior flag to null ("interior": null,) it prevents that location JSON from being loaded, providing the following error in the Notification feed: Warning: Unable to load Location SuperStarCafe_Lancaster.json: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'interior', line 10, position 20
the JSON in question has been attached for analysis.
[SuperStarCafe_Lancaster.json.txt](https://github.com/justalemon/FoodShops/files/7073549/SuperStarCafe_Lancaster.json.txt) The Wiki says that this should work, so I'm not sure why it's not accepting the null flag and disabling the interior check. Not sure if I'm doing this wrong or what, but it's definitely a niche feature so I can see this  slipping under the radar. Thanks for looking into this and providing any help you can!

**Comment by justalemon** [comment]
I was about to go to sleep.

Ill fix this one once I wake up :)

**Comment by Hydraxonn** [comment]
haha excellent, thank you. I'll be happy to help with any testing you need!

**Comment by justalemon** [comment]
@Hayden-Purificato Can you try [this build](https://ci.appveyor.com/api/buildjobs/sjf04179kf1e4yyn/artifacts/FoodShops.7z) to see if it works?

By the way, I had a fix for this but it wasn't pushed to GitHub for some reason xd

**Comment by Hydraxonn** [comment]
Yes, I can confirm that the version you've provided fixes the issue. Now to fix all my Location JSONs! Thank you again!
