### ISSUE TITLE
Servers don’t spawn behind counter

### ISSUE THREAD

**Issue by ClassAFelony** [justalemon/FoodShops#8]
The cashiers at all of the restaurants besides the bean machine don’t spawn behind the register but instead spawn next outside of the restaurant building exterior.

**Comment by justalemon** [comment]
This happens because the collisions don't load fast enough.

**Comment by justalemon** [comment]
This should be fixed in e25c4516be019bced5c4b2dbcaf72229b4f3e674. I'm doing a bit more testing just to make sure.

You can download a test build from https://ci.appveyor.com/api/buildjobs/gs633o9js0mwgwyv/artifacts/FoodShops.7z

**Comment by justalemon** [comment]
Fixed by 55012d337910143a3f693d896e8f52cf4ef26669
